language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: "TEyQojoNThhRnlBfv8gWM7EEGNm6AJ35hMZWHw5gMaL0tre6g+t3PBXnGRhxnAbVnzGzKuRA9kdk8oPVJiT8fDW+PzWA0NyMZWxKqXtlIL52OgsJYXhNnzGXTcnEwLAC5Bz3gJ5i+D8C4+WrgHw/h0BB2097BSkU63jZcEjn/ldfnPeWXJ46wYzkfVUbNCYlAeOSaNLkoV6UmKQUo/OLs79aFqZsyjLGAI28KIdoaJCPPMn7VAkEzpMSSGIIPVFzesNMG3ZT5YxX4NKjIFOD6VHRHIeXggKXDSy9TtxOnAdRXBENttrqTQ2A7BdL2Brj8SxPMVbUeXmuYgu0CDWR746a2e8ISBOM1vRKWlYC6MrKoqw0gEE0XrhIgkW9+QbyJb++rLBmNhahHMrqxyGJT45C24TthejwpBPunkZHRDwhRS1Qs+FMvxE8ZIrZkLbflo7oViW3RpqUZtZLcNBfqVIBXuvMcEktYrwk7cj2jWe5b+X9fEd0Bx81AFmBZdIhPXvSef0eCK/K/S9a20XvoIsKVGbm9OhuIzWFCnmf5XFEFRFepTHHL6atO2bbE8X/wgiFulsrrYjZTuTAyxYg34CasO59cjpt/2d3aP70McJjsmRQRhp7DyNlHMx6EE2M3QrlORhl8ljD+Pr79Zs4BaqPhkCboRv8xbQX27HRCcQ="
jdk:
  - oraclejdk8
script:
  - mvn clean test sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
after_success:
  - bash <(curl -s https://codecov.io/bash)